### ISSUE TITLE
Moodle H5P integration doesn't work.

### ISSUE THREAD

**Issue by carbasemin** [trax-project/moodle-trax-logs#11]
Using docker image docker.io/bitnami/moodle:4

Modified `/bitnami/moodle/theme/boost/config.php` as suggested in H5P integration and added the line

```
$THEME->javascripts_footer = array('../../admin/tool/log/store/trax/javascript/catch_hvp_events');
```

but wasn't able make it work.

Here https://docs.moodle.org/dev/Themes_overview it says that javascripts_footer shouldn't be used anymore and instead AMD Javascript Modules should be used. We also tried adding the script to `config.php` with

```
$PAGE->requires->js_call_amd('../../admin/tool/log/store/trax/javascript/catch_hvp_events', 'catchH5PEvents');
```

as suggested in moodle documentation but that didn't work either.

**Comment by sfraysse** [comment]
This plugin has not been upgraded to support Moodle 4.x yet.

**Comment by carbasemin** [comment]
Upon reading the reply, we tried:

- moodle:3.11.8 with Trax Logs v0.20
- moodle:3.9.0 with Trax Logs v0.20

the same problem continues; we can get core_* events like \core\event\user_loggedin and \core\event\course_viewed in our LRS but H5P integration still doesn't work.

Also tried

- moodle:3.7.0 with v0.19 but this time the plugin didn't work at all. Tried various configurations but got nothing, not even core_* events.

**Comment by sfraysse** [comment]
Hi,
Trax Logs v0.20 has been developed for Moodle 3.9.
Please, try to use the last version of 3.9 (not 3.9.0).
They may have been changes regarding H5P during a 3.9 minor update.

**Comment by carbasemin** [comment]
Tried:

v0.20 with Moodle 3.9.2, which was the latest 3.9 version. Still, we can't get the H5P info, e.g., student attempts at a multiple question quiz, which are available at https://moodleurl/mod/h5pactivity/report.php?studentinfo

**Comment by sfraysse** [comment]
Ok, difficult to say what happens because there are 3 main areas where issues could occur:
- The JS and its integration whith your theme: try to insert `console.log(...)` in the JS script to see if it detects the H5P events.
- The requests from JS to the back-end: try to observe network requests when the user interacts.
- The exchanges with the LRS: as you already receives other statements, it should work but there may be a validation issue. What LRS are you using?

**Comment by carbasemin** [comment]
It's very likely that our problem is the first one. Here are the logs generated when we replied to a H5P multiple question content (debug is set to DEVELOPER in Moodle settings):

```
[php7:warn] [pid 141] [client 172.21.0.1:36776] PHP Warning:  array_merge() expects at least 1 parameter, 0 given in /bitnami/moodle/admin/tool/log/store/trax/classes/src/config.php on line 325, referer: https://<moodle_url>/h5p/embed.php?url=https%3A%2F%2F<moodle_url>%2Fpluginfile.php%2F37%2Fmod_h5pactivity%2Fpackage%2F0%2Fmultiple-choice-2.h5p&preventredirect=1&component=mod_h5pactivity&export=1&embed=1&copyright=1

[php7:warn] [pid 141] [client 172.21.0.1:36776] PHP Warning:  array_merge(): Expected parameter 3 to be an array, null given in /bitnami/moodle/admin/tool/log/store/trax/classes/src/config.php on line 327, referer: https://<moodle_url>/h5p/embed.php?url=https%3A%2F%<moodle_url>%2Fpluginfile.php%2F37%2Fmod_h5pactivity%2Fpackage%2F0%2Fmultiple-choice-2.h5p&preventredirect=1&component=mod_h5pactivity&export=1&embed=1&copyright=1

[php7:warn] [pid 141] [client 172.21.0.1:36776] PHP Warning:  in_array() expects parameter 2 to be array, null given in /bitnami/moodle/admin/tool/log/store/trax/classes/src/services/statements.php on line 139, referer: https://<moodle_url>/h5p/embed.php?url=https%3A%2F%2F<moodle_url>%2Fpluginfile.php%2F37%2Fmod_h5pactivity%2Fpackage%2F0%2Fmultiple-choice-2.h5p&preventredirect=1&component=mod_h5pactivity&export=1&embed=1&copyright=1
172.21.0.1 - - 

"POST /lib/ajax/service.php?sesskey=YaF9bS6geH&info=core_xapi_statement_post HTTP/1.0" 200 31
```

Nothing related to what we're trying to print with `console.log(...)` in `catch_hvp_events.js`.

Here's our `/bitnami/moodle/theme/boost/config.php`:

```
<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Boost config.
 *
 * @package   theme_boost
 * @copyright 2016 Frédéric Massart
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

require_once(__DIR__ . '/lib.php');

$THEME->name = 'boost';
$THEME->sheets = [];
$THEME->editor_sheets = [];
$THEME->editor_scss = ['editor'];
$THEME->usefallback = true;
$THEME->scss = function($theme) {
    return theme_boost_get_main_scss_content($theme);
};

$THEME->layouts = [
    // Most backwards compatible layout without the blocks - this is the layout used by default.
    'base' => array(
        'file' => 'columns2.php',
        'regions' => array(),
    ),
    // Standard layout with blocks, this is recommended for most pages with general information.
    'standard' => array(
        'file' => 'columns2.php',
        'regions' => array('side-pre'),
        'defaultregion' => 'side-pre',
    ),
    // Main course page.
    'course' => array(
        'file' => 'columns2.php',
        'regions' => array('side-pre'),
        'defaultregion' => 'side-pre',
        'options' => array('langmenu' => true),
    ),
    'coursecategory' => array(
        'file' => 'columns2.php',
        'regions' => array('side-pre'),
        'defaultregion' => 'side-pre',
    ),
    // Part of course, typical for modules - default page layout if $cm specified in require_login().
    'incourse' => array(
        'file' => 'columns2.php',
        'regions' => array('side-pre'),
        'defaultregion' => 'side-pre',
    ),
    // The site home page.
    'frontpage' => array(
        'file' => 'columns2.php',
        'regions' => array('side-pre'),
        'defaultregion' => 'side-pre',
        'options' => array('nonavbar' => true),
    ),
    // Server administration scripts.
    'admin' => array(
        'file' => 'columns2.php',
        'regions' => array('side-pre'),
        'defaultregion' => 'side-pre',
    ),
    // My dashboard page.
    'mydashboard' => array(
        'file' => 'columns2.php',
        'regions' => array('side-pre'),
        'defaultregion' => 'side-pre',
        'options' => array('nonavbar' => true, 'langmenu' => true, 'nocontextheader' => true),
    ),
    // My public page.
    'mypublic' => array(
        'file' => 'columns2.php',
        'regions' => array('side-pre'),
        'defaultregion' => 'side-pre',
    ),
    'login' => array(
        'file' => 'login.php',
        'regions' => array(),
        'options' => array('langmenu' => true),
    ),

    // Pages that appear in pop-up windows - no navigation, no blocks, no header.
    'popup' => array(
        'file' => 'columns1.php',
        'regions' => array(),
        'options' => array('nofooter' => true, 'nonavbar' => true),
    ),
    // No blocks and minimal footer - used for legacy frame layouts only!
    'frametop' => array(
        'file' => 'columns1.php',
        'regions' => array(),
        'options' => array('nofooter' => true, 'nocoursefooter' => true),
    ),
    // Embeded pages, like iframe/object embeded in moodleform - it needs as much space as possible.
    'embedded' => array(
        'file' => 'embedded.php',
        'regions' => array()
    ),
    // Used during upgrade and install, and for the 'This site is undergoing maintenance' message.
    // This must not have any blocks, links, or API calls that would lead to database or cache interaction.
    // Please be extremely careful if you are modifying this layout.
    'maintenance' => array(
        'file' => 'maintenance.php',
        'regions' => array(),
    ),
    // Should display the content and basic headers only.
    'print' => array(
        'file' => 'columns1.php',
        'regions' => array(),
        'options' => array('nofooter' => true, 'nonavbar' => false),
    ),
    // The pagelayout used when a redirection is occuring.
    'redirect' => array(
        'file' => 'embedded.php',
        'regions' => array(),
    ),
    // The pagelayout used for reports.
    'report' => array(
        'file' => 'columns2.php',
        'regions' => array('side-pre'),
        'defaultregion' => 'side-pre',
    ),
    // The pagelayout used for safebrowser and securewindow.
    'secure' => array(
        'file' => 'secure.php',
        'regions' => array('side-pre'),
        'defaultregion' => 'side-pre'
    )
];

$THEME->parents = [];
$THEME->enable_dock = false;
$THEME->csstreepostprocessor = 'theme_boost_css_tree_post_processor';
$THEME->extrascsscallback = 'theme_boost_get_extra_scss';
$THEME->prescsscallback = 'theme_boost_get_pre_scss';
$THEME->precompiledcsscallback = 'theme_boost_get_precompiled_css';
$THEME->yuicssmodules = array();
$THEME->rendererfactory = 'theme_overridden_renderer_factory';
$THEME->requiredblocks = '';
$THEME->addblockposition = BLOCK_ADDBLOCK_POSITION_FLATNAV;
$THEME->iconsystem = \core\output\icon_system::FONTAWESOME;
$THEME->javascripts_footer = array('../../admin/tool/log/store/trax/javascript/catch_hvp_events');

```

When we `cat ../../admin/tool/log/store/trax/javascript/catch_hvp_events.js` from the directory where this `config.php` file lives, we do get the desired file, `catch_hvp_events.js`, that is:

```
// We wait until the page is loaded to check that JQuery exists.
// This is not always the case. But it always exists on H5P pages.

window.addEventListener("load", function(event) {
    catchH5PEvents();
    console.log('window stuff, load the function. lalala')
});

catchH5PEvents = function () {
    console.log('catch h5p events. lalala')
    if (window.$) {

.
.
.
```

**Comment by carbasemin** [comment]
To reply to your third question, we're using LRSQL from Yet Analytics. We did consider Trax LRS but there wasn't a Docker image for it.

It's highly likely that if we're able to make the plugin work, we'd use Trax LRS too, perhaps with building our own Docker image.

**Comment by sfraysse** [comment]
Hi,
You are using:
```
$THEME->javascripts_footer = array('../../admin/tool/log/store/trax/javascript/catch_hvp_events');
```
Please, could you try to use:
```
$THEME->javascripts_footer = array('../../../admin/tool/log/store/trax/javascript/catch_hvp_events');
```
as stated in the documentation and as it is running in my installation.

**Comment by carbasemin** [comment]
That was the very first thing we tried, of course. There's nothing on that path though. In my installation -and perhaps it's different because it's a Docker container- `catch_hvp_events.js` is located at `../..` and not `../../..`. 

We tried again, just in case, but the result is exactly the same as our second last comment - we can't see anything related to what we want in logs. I't's probably a JS/theme integration issue as you've stated.

**Comment by sfraysse** [comment]
Please, could you test something:

- Use `$THEME->javascripts_footer = array('../../../admin/tool/log/store/trax/javascript/catch_hvp_events');` again.
- Do it with the default `Boost` theme to avoid any specificity. 
- Insert `console.log('LOADED !!!!');` at the begining of the `catch_hvp_events.js` file.
- Purge all caches (link at the end of your admin page).
- Open an H5P page in Moodle and check your console.

The reason of the `../../..` is that the JS file is not located relatively to the theme config file, but to the theme javascript folder.

**Comment by sfraysse** [comment]
And please, check the "footer" JS in your browser dev tools to see if it contains the right JS code, like in this capture...

<img width="673" alt="Capture" src="https://user-images.githubusercontent.com/14231525/188457824-9936cbb1-e15c-4303-9f55-0e8089806dfa.PNG">

**Comment by carbasemin** [comment]
Tried exactly what you've proposed; JS file is not loaded at all. Here's the screen capture:

- 
![Screenshot from 2022-09-05 19-40-49](https://user-images.githubusercontent.com/75378430/188490885-e58fcf8a-7bde-4d31-bda6-852ddf074963.png)

Thank you for the explanation of the need for the three parent redirects, i.e., `../../..`. I couldn't figure out what you've meant by "theme javascript folder" though. Here's the folder where I am making the changes for reference:

```
root@b5034cd15fe0:/bitnami/moodle/theme/boost# ls
amd  classes  cli  config.php  lang  layout  lib.php  pix  readme_moodle.txt  scss  settings.php  style  templates  tests  thirdpartylibs.xml  upgrade.txt  version.php
```

**Comment by carbasemin** [comment]
Tried exactly what you've proposed; JS file is not loaded at all. Here's the screen capture:

![Screenshot from 2022-09-05 19-40-49](https://user-images.githubusercontent.com/75378430/188491559-312076dc-e748-496c-8ab8-0705a48c8b2a.png)

Thank you for the explanation of the need for the three parent redirects, i.e., `../../..`. I couldn't figure out what you've meant by "theme javascript folder" though. Here's the folder where I am making the changes for reference:

```
root@b5034cd15fe0:/bitnami/moodle/theme/boost# ls
amd  classes  cli  config.php  lang  layout  lib.php  pix  readme_moodle.txt  scss  settings.php  style  templates  tests  thirdpartylibs.xml  upgrade.txt  version.php
```

**Comment by sfraysse** [comment]
Your capture does not show any script...

**Comment by carbasemin** [comment]
Because I've searched "foo" in the scripts and there was nothing there. Here's the full thing:

![Screenshot from 2022-09-06 11-07-12](https://user-images.githubusercontent.com/75378430/188581952-ccd829dd-92fb-4f53-9e0c-48efff325436.png)
![Screenshot from 2022-09-06 11-07-18](https://user-images.githubusercontent.com/75378430/188581973-d212c807-103f-4942-9d08-064182c9a52f.png)

**Comment by sfraysse** [comment]
Are you using the default Boost theme?

**Comment by carbasemin** [comment]
Yes we are.

![2022-09-07-12-04-moodle melda io](https://user-images.githubusercontent.com/75378430/188838289-d842a832-8473-442f-9c74-eb209d03721c.png)

**Comment by sfraysse** [comment]
I don't know what to say. If you are using the lastest Moodle 3.9 with Boost and you add a script on the footer, you should see this script in your console. You should start by this, independently of TRAX Logs. And next, add the TRAX Logs script and check that it is loaded.

Just in case, you said before:
> v0.20 with Moodle 3.9.2, which was the latest 3.9 version

I don't think so...

**Comment by carbasemin** [comment]
> Tried exactly what you've proposed; JS file is not loaded at all. Here's the screen capture:
> 
> ![Screenshot from 2022-09-05 19-40-49](https://user-images.githubusercontent.com/75378430/188491559-312076dc-e748-496c-8ab8-0705a48c8b2a.png)
> 
> Thank you for the explanation of the need for the three parent redirects, i.e., `../../..`. I couldn't figure out what you've meant by "theme javascript folder" though. Here's the folder where I am making the changes for reference:
> 
> ```
> root@b5034cd15fe0:/bitnami/moodle/theme/boost# ls
> amd  classes  cli  config.php  lang  layout  lib.php  pix  readme_moodle.txt  scss  settings.php  style  templates  tests  thirdpartylibs.xml  upgrade.txt  version.php
> ```

After detailed investigation, we found out that the problem was the last paragraph; there's no "theme javascript folder." We created an empty file called `javascript` and it suddenly worked. Because the filepath is accurate now.
