### ISSUE TITLE
Asynchronous mode is not functional

### ISSUE THREAD

**Issue by naudinthomas** [trax-project/moodle-trax-logs#5]
Moodle version : 3.6.2+ (Build: 2019012400)
Plugin Trax version : v0.14 (Build: 2018050814)

LRS : Learning Locker v2.5.5

Hello,

If the events logs are correctly sent in synchronous mode, nothing is sent in asynchronous mode, during the execution of the CRON or even with the use of the task "\logstore_trax\task\sync_task".
Attached, the plugin's configuration. Is there a misconfigured value ?

actors_identification : 1
xis_anonymization : 0
firstlogs : 18/11/2019
core_events authentication,navigation,completion,grading
moodle_components : mod_assign,mod_book,mod_chat,mod_choice,mod_data,mod_feedback,mod_folder,mod_forum,mod_glossary,mod_imscp,mod_lesson,mod_lti,mod_page,mod_quiz,mod_resource,mod_scorm,mod_survey,mod_url,mod_wiki,mod_workshop
additional_components : mod_hvp,other
resend_livelogs_until : 17/11/2019
sync_mode : 1
attempts :  4
db_batch_size : 100
xapi_batch_size : 10

**Comment by sfraysse** [comment]
Please, could you take a look at the "logstrore_trax_logs" table in your database... 
Is it empty? Or are there some entries?
If there are entries, could you check the error column and tell me what you see?
Are there some entries with error = 0 or not?
What error values do you see?

**Comment by naudinthomas** [comment]
The error codes in the "logstore_trax_logs" table have the following values:
code 0: 65 occurrences
code 2: 19 occurrences
code 3: 2 occurrences
code 4: 960 occurrences

**Comment by sfraysse** [comment]
Code 0 means that a batch of statements has been successfully sent to your LRS (asynchronous, with a 200 response code). So you should have some statements in your LRS. Some ideas to go further:
- Check your LRS: are you sure there is no statement?
- Check the logs of your LRS (if available)
- Try with another LRS
